CREATE TABLE session (
	id VARCHAR(100) NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4;

CREATE TABLE users (
	id BIGINT NOT NULL AUTO_INCREMENT,
	session_id VARCHAR(100) NOT NULL,
	user VARCHAR(100) NOT NULL,
	story_points INT NOT NULL DEFAULT 0,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id),
	UNIQUE KEY uq_session_user (session_id, user),
	CONSTRAINT fk_users_session
		FOREIGN KEY (session_id)
		REFERENCES session(id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4;
